%% Import 0D data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/awing/Dropbox/RCEMIP_local/0Dstatistics/toshare/Table_A1_RCE_small295.csv
%
% Auto-generated by MATLAB on 06-Dec-2022 12:22:40

clear all
%% Load precipitating water path
load('/Users/awing/Dropbox/RCEMIP_local/RH_stability/precippath.mat') %plwivi295 %mm

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 17);

% Specify range and delimiter
opts.DataLines = [2, 43];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "Model", "F_NET", "R_TOA", "Q_OCN", "R_NET", "OLR", "ASR_TOA", "LHF", "SHF", "PW", "Precip", "LWP", "IWP", "clwvi_avg", "LapseRate"];
opts.VariableTypes = ["double", "char", "char", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["VarName2", "Model"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["VarName2", "Model"], "EmptyFieldRule", "auto");

%% RCE_small295
% Import the data
TableA1RCEsmall295 = readtable("/Users/awing/Dropbox/RCEMIP_local/0Dstatistics/toshare/Table_A1_RCE_small295.csv", opts);

%% Convert to output type
TableA1RCEsmall295 = table2cell(TableA1RCEsmall295);
numIdx = cellfun(@(x) ~isnan(str2double(x)), TableA1RCEsmall295);
TableA1RCEsmall295(numIdx) = cellfun(@(x) {str2double(x)}, TableA1RCEsmall295(numIdx));

precip295 = cell2mat(TableA1RCEsmall295(:,13)); %mm d^-1 precip
clwivi295 = cell2mat(TableA1RCEsmall295(:,16)); %mm total cloud water (cloud liquid water + cloud ice)

%% Clear temporary variables
clear opts

%% Compute precipitation efficiency
PE295 = precip295./(clwivi295+plwivi295'); %Precip/(clwvi_avg + plwivi)= mm d^-1/mm = d^-1
PE295 = PE295./86400; %convert from d^-1 to s^-1

%% RCE_small300
%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 17);

% Specify range and delimiter
opts.DataLines = [2, 43];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "Model", "F_NET", "R_TOA", "Q_OCN", "R_NET", "OLR", "ASR_TOA", "LHF", "SHF", "PW", "Precip", "LWP", "IWP", "clwvi_avg", "LapseRate"];
opts.VariableTypes = ["double", "char", "char", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["VarName2", "Model"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["VarName2", "Model"], "EmptyFieldRule", "auto");
% Import the data
TableA1RCEsmall300 = readtable("/Users/awing/Dropbox/RCEMIP_local/0Dstatistics/toshare/Table_A1_RCE_small300.csv", opts);

%% Convert to output type
TableA1RCEsmall300 = table2cell(TableA1RCEsmall300);
numIdx = cellfun(@(x) ~isnan(str2double(x)), TableA1RCEsmall300);
TableA1RCEsmall300(numIdx) = cellfun(@(x) {str2double(x)}, TableA1RCEsmall300(numIdx));

precip300 = cell2mat(TableA1RCEsmall300(:,13)); %mm d^-1 precip
clwivi300 = cell2mat(TableA1RCEsmall300(:,16)); %mm total cloud water (cloud liquid water + cloud ice)

%% Clear temporary variables
clear opts

%% Compute precipitation efficiency
PE300 = precip300./(clwivi300+plwivi300'); %Precip/(clwvi_avg + plwivi)= mm d^-1/mm = d^-1
PE300 = PE300./86400; %convert from d^-1 to s^-1

%% RCE_small305
%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 17);

% Specify range and delimiter
opts.DataLines = [2, 43];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "Model", "F_NET", "R_TOA", "Q_OCN", "R_NET", "OLR", "ASR_TOA", "LHF", "SHF", "PW", "Precip", "LWP", "IWP", "clwvi_avg", "LapseRate"];
opts.VariableTypes = ["double", "char", "char", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["VarName2", "Model"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["VarName2", "Model"], "EmptyFieldRule", "auto");
% Import the data
TableA1RCEsmall305 = readtable("/Users/awing/Dropbox/RCEMIP_local/0Dstatistics/toshare/Table_A1_RCE_small305.csv", opts);

%% Convert to output type
TableA1RCEsmall305 = table2cell(TableA1RCEsmall305);
numIdx = cellfun(@(x) ~isnan(str2double(x)), TableA1RCEsmall305);
TableA1RCEsmall305(numIdx) = cellfun(@(x) {str2double(x)}, TableA1RCEsmall305(numIdx));

precip305 = cell2mat(TableA1RCEsmall305(:,13)); %mm d^-1 precip
clwivi305 = cell2mat(TableA1RCEsmall305(:,16)); %mm total cloud water (cloud liquid water + cloud ice)

%% Clear temporary variables
clear opts

%% Compute precipitation efficiency
PE305 = precip305./(clwivi305+plwivi305'); %Precip/(clwvi_avg + plwivi)= mm d^-1/mm = d^-1
PE305 = PE305./86400; %convert from d^-1 to s^-1

%% Export model names
small_model_list = TableA1RCEsmall305(:,3);

save('PEproxy_cwipwi.mat','PE295','PE300','PE305','small_model_list')

